kind: pipeline
name: default

steps:
- name: test
  image: python
  commands:
  - pip install -r requirements.txt
  - pytest 

- name: notify
  image: appleboy/drone-discord
  settings:
    webhook_id: 714270759157235764/FZDb6JmQ22QVfFtg4A01HDZLdt
    webhook_token: 7sYfSGehJBVSB7JPGCjVnbVaZM8FfK9G3o7S4FmJf
    message: "Testing from drone image"
