kind: pipeline
name: default

steps:
- name: test
  image: python
  commands:
  - pip install -r requirements.txt
  - pytest
 

- name: notify
  image: drillster/drone-email
  settings:
    host: smtp.office365.com
    port: 587
    username: demesio.silva@outlook.com
    password: demesio1250
    from: noreply@github.com
    recipients:
      - octocat@github.com  
      - marcosricardoss@gmail.com
      - the-admin@your-domain.com
    when:
      status: 
        - changed
        - failure