kind: pipeline
name: default

steps:
- name: test
  image: python
  commands:
  - pip install -r requirements.txt
  - pytest 
  when:
    branch:
    - master
    - dev

- name: notify
  image: appleboy/drone-discord
  settings:
    webhook_id: 
      from_secret: discord_webhook_id
    webhook_token: 
      from_secret: discord_webhook_token
    username: drone.io
    message: >
      {{#success build.status}}
        build {{build.number}} succeeded. Good job.
      {{else}}
        build {{build.number}} failed. Fix me please.
      {{/success}}
  when:
    branch:
    - master
    - dev      