kind: pipeline
name: default

steps:
- name: test
  image: python
  commands:
  - pip install -r requirements.txt
  - pytest

notify:
  image: drillster/drone-email
  host: smtp.some-server.com
  username: foo
  password: bar
  from: drone@your-domain.com
  recipients: [ the-admin@your-domain.com, octocat@your-domain.com ]
  when:
    status: [ changed, failure ]  