kind: pipeline
name: default

steps:
- name: test
  image: python
  commands:
  - pip install -r requirements.txt
  - pytest

notify:
  image: drillster/drone-email
  host: smtp.gmail.com
  port: 587
  username: marcosricardoss
  password: mr2s2083
  skip_verify: true 
  from: drone@your-domain.com
  recipients: [ marcosricardoss@gmail.com, the-admin@your-domain.com, octocat@your-domain.com ]
  when:
    status: [ changed, failure ]  