kind: pipeline
type: exec
name: deploy

platform:
  os: linux
  arch: amd64

steps:
- name: greeting
  commands:  
  - ls
  - pwd
  - hostname
  - echo $HOME
  - docker-compose down --remove-orphans
  - docker-compose up -d
