kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: greeting
  commands:
  - apt install curl  
  - echo hello world
  - echo deploy.txt  
  - curl -X POST --data-urlencode "payload={\"channel\": \"#dev\", \"username\": \"$HOSTNAME\", \"text\": \"Deploy process completed.\"}" from_secret: slack_webhook_url
  depends_on:
    - default