kind: pipeline
name: default

steps:
- name: test
  image: python
  commands:
  - pip install -r requirements.txt
  - pytest 

- name: notify
  image: plugins/slack
  settings:
    webhook: https://hooks.slack.com/services/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
    channel: dev 
