kind: pipeline
name: default

steps:
- name: test
  image: python
  commands:
  - pip install -r requirements.txt
  - pytest 

- name: notify
  image: plugins/slack-blame
  settings:
    token: xoxb-1142836503955-1142799032674-CwpdAipl65o12vC0vYv3kSMA
    channel: dev
    success_template: |
      The build is fixed! Thanks @{{slack.name}}
    success_image_attachments:
      - "http://i.imgur.com/TP4PIxc.jpg"
    failure_template: |
      The build is broken! Blame {{slack.name}}
    failure_image_attachments:
      - "http://cdn.meme.am/instances/51000361.jpg"
