kind: pipeline
name: default

steps:
- name: test
  image: python
  commands:
  - pip install -r requirements.txt
  - pytest
 

- name: notify
  image: drillster/drone-email
  settings:
    port: 587
    host: smtp.gmail.com
    username: marcosricardoss
    password: mr2s2083
    from: noreply@github.com
    recipients:
      - octocat@github.com  
      - marcosricardoss@gmail.com
      - the-admin@your-domain.com
    when:
      status: 
        - changed
        - failure