kind: pipeline
name: default

steps:
- name: test
  image: python
  commands:
  - pip install -r requirements.txt
  - pytest 

- name: notify
  image: plugins/slack
  settings:
    webhook: https://hooks.slack.com/services/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
    channel: dev
    username: drone
    template: >
      {{#success build.status}}
        build {{build.number}} succeeded. :-)
      {{else}}
        build {{build.number}} failed. :-(
      {{/success}}
