kind: pipeline
name: default

steps:
- name: test
  image: python
  commands:
  - pip install -r requirements.txt
  - pytest 

- name: notify discord 
  image: appleboy/drone-discord
  settings:
    webhook_id: 
      from_secret: discord_webhook_id
    webhook_token: 
      from_secret: discord_webhook_token
    username: drone.io
    message: >
      {{#success build.status}}
      :thumbsup: build {{build.number}} succeeded. Good job. (type: `{{ build.event }}`)
      {{else}}
      :thumbsdown: build {{build.number}} failed. Fix me please. (type: `{{ build.event }}`)
      {{/success}}            
      build page: {{ build.link }}
  # when:
  #   branch:
  #   - master

- name: notify slack
  image: plugins/slack
  settings:
    webhook: 
      from_secret: slack_webhook_url
    username: drone
    channel: dev
    template: >
      {{#if build.pull }}
        *{{#success build.status}}✔{{ else }}✘{{/success}} {{ uppercasefirst build.status }}*: <https://github.com/{{ repo.owner }}/{{ repo.name }}/pull/{{ build.pull }}|Pull Request #{{ build.pull }}>
      {{else}}
        *{{#success build.status}}✔{{ else }}✘{{/success}} {{ uppercasefirst build.status }}: Build #{{ build.number }}* (type: `{{ build.event }}`)
      {{/if}}

      Commit: <https://github.com/{{ repo.owner }}/{{ repo.name }}/commit/{{ build.commit }}|{{ truncate build.commit 8 }}>

      Branch: <https://github.com/{{ repo.owner }}/{{ repo.name }}/commits/{{ build.branch }}|{{ build.branch }}>

      Author: {{ build.author }}
      
      <{{ build.link }}|Visit build page ↗>
  # when:
  #   branch:
  #   - master

- name: notify slack app
  image: plugins/slack-blame
  settings:
    token:
      from_secret: slack-app-token
    channel: dev
    success_template: |
      The build is fixed! Thanks @{{slack.name}}
    success_image_attachments:
      - "http://i.imgur.com/TP4PIxc.jpg"
    failure_template: |
      The build is broken! Blame {{slack.name}}
    failure_image_attachments:
      - "http://cdn.meme.am/instances/51000361.jpg"    
  when:
    branch:
    - master