version: '3.2'
services:
  app:
    container_name: flaskapp
    build:
      context: .
    environment:
        FLASK_APP: app        
    restart: always
    command: waitress-serve --port=4000 --call 'app:create_app'
    volumes:
      - './:/usr/src/app'
    ports:
      - '4000:4000'
      
  # webhookrelay:
  #   container_name: webhookrelay
  #   image: webhookrelay/webhookrelayd:latest
  #   network_mode: host
  #   command:
  #     - --mode 
  #     - tunnel 
  #     - --region 
  #     - us-west
  #   restart: always
  #   depends_on:
  #     - app
  #   environment: 
  #     - RELAY_KEY=${RELAY_KEY}
  #     - RELAY_SECRET=${RELAY_SECRET}
  #     - TUNNELS=${TUNNELS} 
