version: '3'
services:
  app:
    build:
      context: .
    environment:
        FLASK_APP: app        
    command: python3 -m flask run --host=0.0.0.0 --port=8000
    volumes:
      - './:/usr/src/app'
    ports:
      - '8000:8000'
