version: '3.2'
services:
  app:
    container_name: flaskapp
    build:
      context: .
    environment:
        FLASK_APP: app        
    command: python3 -m flask run --host=0.0.0.0 --port=4000
    volumes:
      - './:/usr/src/app'
    ports:
      - '4000:4000'
      
  # webhookrelay:
  #   container_name: webhookrelay
  #   image: webhookrelay/webhookrelayd:latest
  #   network_mode: host
  #   command:
  #     - --mode 
  #     - tunnel 
  #     - --region 
  #     - us-west
  #   restart: always
  #   depends_on:
  #     - app
  #   environment: 
  #     - RELAY_KEY=${RELAY_KEY}
  #     - RELAY_SECRET=${RELAY_SECRET}
  #     - TUNNELS=${TUNNELS} 
