#!/usr/bin/env bash

curl -X POST --data-urlencode "payload={\"channel\": \"#dev\", \"username\": \"webhookbot\", \"text\": \"Build was successfully deployed ${HOSTNAME}\", \"icon_emoji\": \":ghost:\"}" https://hooks.slack.com/services/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